apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dashboard-local

resources:
  - mailpit.yaml
  - ../../base
  - namespace.yaml
  - laravel-volumes.yaml

patches:
  - path: deployment-patch.yaml
  - path: ingress-patch.yaml
