apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: console-laravel-storage-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: console-laravel-data-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: laravel-config
data:
  APP_ENV: production
  APP_DEBUG: "false"
  APP_URL: "https://console.dev.test"
  ASSET_URL: "https://console.dev.test"
  DB_CONNECTION: "sqlite"
  DB_DATABASE: "/var/lib/larakube/database.sqlite"
  AUTORUN_LARAVEL_MIGRATION_SKIP_DB_CHECK: "true"
  CACHE_STORE: "database"
  SESSION_DRIVER: "database"
  QUEUE_CONNECTION: "database"
  BOOST_PHP_EXECUTABLE_PATH: "&quot;larakube php&quot;"
  BOOST_COMPOSER_EXECUTABLE_PATH: "&quot;larakube composer&quot;"
  BOOST_NPM_EXECUTABLE_PATH: "&quot;larakube npm&quot;"
  BOOST_VENDOR_BIN_EXECUTABLE_PATH: "&quot;larakube art&quot;"
